### ISSUE TITLE
Dokumentace postupu instalace

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CDArcha-server#18]
Prosím o stručný popis instalace do wiki.

**Comment by cosmo-cz** [comment]
Zatím takto. Psal jsem to v průběhu roku a ještě jsem nedělal zkoušku správnosti.
https://github.com/moravianlibrary/CDArcha-server/wiki/CDArcha_single_server_instalace

**Comment by zabak** [comment]
Díky
