### ISSUE TITLE
Připojit archiv do vašeho adresáře - jak ho odpojím?

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/CDArcha-server#44]
Když si připojím archiv, kde uvidím přehled připojených archivů a jak si archiv zase odpojím?

**Comment by cosmo-cz** [comment]
Ikony připojit a odpojit jsou vedle sebe.
Ikona připojit připojí konkrétní archiv do adresáře /mnt/cdarcha/share (symlink).
Pro zapojení této funkce je nutné nastavit v databáze, nená momentálně webovou konfiguraci.
Ikona odpojit odpojí všechny archivy.
Bylo to zamýšlěno jako ulehčení pro ty co mají přístup na SSH.
